### ISSUE TITLE
Shiny Web App

### ISSUE THREAD

**Issue by JoGraesslin** [dsturg/PancrESS#1]
Hello,
I am unable to use your web app (https://transcriptomics.shinyapps.io/PancrESSdb/) as I can not scroll down to genes not starting with an 'A'.
Best,
Jo

**Comment by dsturg** [comment]
Thanks Jo for reporting!
That behavior is the same for me. I will investigate if it is something I can change.  You should still be able to type in a gene symbol and have it some up without scrolling; e.g. "INS".
Summary data is provided in the supplemental tables of the manuscript as well. Those could be used to scroll through for gene symbols. Note that the supplemental tables are more comprehensive than the shiny app, due to performance limits on the server that hosts it, so some gene symbols will not be included in both.
Best regards,
Dave

**Comment by JoGraesslin** [comment]
Thanks for your response. I did not understand that I can type in the gene names in the field as well. Best, Jo
